default_platform(:ios)

platform :ios do
  desc "Push to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: true
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M")
    )

    profile_uuid = ENV["PROVISIONING_PROFILE_UUID"]

    build_app(
      scheme: "SchoolMessage",
      export_method: "app-store",
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='Apple Distribution' PROVISIONING_PROFILE_SPECIFIER='#{profile_uuid}'",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "app.takaoka.com.schoolmessage" => profile_uuid
        }
      }
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
